/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VeiculosRouteImport } from './routes/veiculos'
import { Route as UsuariosRouteImport } from './routes/usuarios'
import { Route as ServicosRouteImport } from './routes/servicos'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as MotoristasRouteImport } from './routes/motoristas'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FinanceiroRouteImport } from './routes/financeiro'
import { Route as DespesasRouteImport } from './routes/despesas'
import { Route as ContasRouteImport } from './routes/contas'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as ComissoesRouteImport } from './routes/comissoes'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicWhatsappRouteImport } from './routes/api/public/whatsapp'
import { Route as ApiPublicHooksDailySummaryRouteImport } from './routes/api/public/hooks/daily-summary'

const VeiculosRoute = VeiculosRouteImport.update({
  id: '/veiculos',
  path: '/veiculos',
  getParentRoute: () => rootRouteImport,
} as any)
const UsuariosRoute = UsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosRoute = ServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const MotoristasRoute = MotoristasRouteImport.update({
  id: '/motoristas',
  path: '/motoristas',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroRoute = FinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const DespesasRoute = DespesasRouteImport.update({
  id: '/despesas',
  path: '/despesas',
  getParentRoute: () => rootRouteImport,
} as any)
const ContasRoute = ContasRouteImport.update({
  id: '/contas',
  path: '/contas',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ComissoesRoute = ComissoesRouteImport.update({
  id: '/comissoes',
  path: '/comissoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWhatsappRoute = ApiPublicWhatsappRouteImport.update({
  id: '/api/public/whatsapp',
  path: '/api/public/whatsapp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksDailySummaryRoute =
  ApiPublicHooksDailySummaryRouteImport.update({
    id: '/api/public/hooks/daily-summary',
    path: '/api/public/hooks/daily-summary',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clientes': typeof ClientesRoute
  '/comissoes': typeof ComissoesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/contas': typeof ContasRoute
  '/despesas': typeof DespesasRoute
  '/financeiro': typeof FinanceiroRoute
  '/login': typeof LoginRoute
  '/motoristas': typeof MotoristasRoute
  '/relatorios': typeof RelatoriosRoute
  '/servicos': typeof ServicosRoute
  '/usuarios': typeof UsuariosRoute
  '/veiculos': typeof VeiculosRoute
  '/api/public/whatsapp': typeof ApiPublicWhatsappRoute
  '/api/public/hooks/daily-summary': typeof ApiPublicHooksDailySummaryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clientes': typeof ClientesRoute
  '/comissoes': typeof ComissoesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/contas': typeof ContasRoute
  '/despesas': typeof DespesasRoute
  '/financeiro': typeof FinanceiroRoute
  '/login': typeof LoginRoute
  '/motoristas': typeof MotoristasRoute
  '/relatorios': typeof RelatoriosRoute
  '/servicos': typeof ServicosRoute
  '/usuarios': typeof UsuariosRoute
  '/veiculos': typeof VeiculosRoute
  '/api/public/whatsapp': typeof ApiPublicWhatsappRoute
  '/api/public/hooks/daily-summary': typeof ApiPublicHooksDailySummaryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/clientes': typeof ClientesRoute
  '/comissoes': typeof ComissoesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/contas': typeof ContasRoute
  '/despesas': typeof DespesasRoute
  '/financeiro': typeof FinanceiroRoute
  '/login': typeof LoginRoute
  '/motoristas': typeof MotoristasRoute
  '/relatorios': typeof RelatoriosRoute
  '/servicos': typeof ServicosRoute
  '/usuarios': typeof UsuariosRoute
  '/veiculos': typeof VeiculosRoute
  '/api/public/whatsapp': typeof ApiPublicWhatsappRoute
  '/api/public/hooks/daily-summary': typeof ApiPublicHooksDailySummaryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clientes'
    | '/comissoes'
    | '/configuracoes'
    | '/contas'
    | '/despesas'
    | '/financeiro'
    | '/login'
    | '/motoristas'
    | '/relatorios'
    | '/servicos'
    | '/usuarios'
    | '/veiculos'
    | '/api/public/whatsapp'
    | '/api/public/hooks/daily-summary'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/clientes'
    | '/comissoes'
    | '/configuracoes'
    | '/contas'
    | '/despesas'
    | '/financeiro'
    | '/login'
    | '/motoristas'
    | '/relatorios'
    | '/servicos'
    | '/usuarios'
    | '/veiculos'
    | '/api/public/whatsapp'
    | '/api/public/hooks/daily-summary'
  id:
    | '__root__'
    | '/'
    | '/clientes'
    | '/comissoes'
    | '/configuracoes'
    | '/contas'
    | '/despesas'
    | '/financeiro'
    | '/login'
    | '/motoristas'
    | '/relatorios'
    | '/servicos'
    | '/usuarios'
    | '/veiculos'
    | '/api/public/whatsapp'
    | '/api/public/hooks/daily-summary'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClientesRoute: typeof ClientesRoute
  ComissoesRoute: typeof ComissoesRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  ContasRoute: typeof ContasRoute
  DespesasRoute: typeof DespesasRoute
  FinanceiroRoute: typeof FinanceiroRoute
  LoginRoute: typeof LoginRoute
  MotoristasRoute: typeof MotoristasRoute
  RelatoriosRoute: typeof RelatoriosRoute
  ServicosRoute: typeof ServicosRoute
  UsuariosRoute: typeof UsuariosRoute
  VeiculosRoute: typeof VeiculosRoute
  ApiPublicWhatsappRoute: typeof ApiPublicWhatsappRoute
  ApiPublicHooksDailySummaryRoute: typeof ApiPublicHooksDailySummaryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/veiculos': {
      id: '/veiculos'
      path: '/veiculos'
      fullPath: '/veiculos'
      preLoaderRoute: typeof VeiculosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/usuarios': {
      id: '/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof UsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos': {
      id: '/servicos'
      path: '/servicos'
      fullPath: '/servicos'
      preLoaderRoute: typeof ServicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/motoristas': {
      id: '/motoristas'
      path: '/motoristas'
      fullPath: '/motoristas'
      preLoaderRoute: typeof MotoristasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro': {
      id: '/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof FinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/despesas': {
      id: '/despesas'
      path: '/despesas'
      fullPath: '/despesas'
      preLoaderRoute: typeof DespesasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contas': {
      id: '/contas'
      path: '/contas'
      fullPath: '/contas'
      preLoaderRoute: typeof ContasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comissoes': {
      id: '/comissoes'
      path: '/comissoes'
      fullPath: '/comissoes'
      preLoaderRoute: typeof ComissoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/whatsapp': {
      id: '/api/public/whatsapp'
      path: '/api/public/whatsapp'
      fullPath: '/api/public/whatsapp'
      preLoaderRoute: typeof ApiPublicWhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/daily-summary': {
      id: '/api/public/hooks/daily-summary'
      path: '/api/public/hooks/daily-summary'
      fullPath: '/api/public/hooks/daily-summary'
      preLoaderRoute: typeof ApiPublicHooksDailySummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClientesRoute: ClientesRoute,
  ComissoesRoute: ComissoesRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  ContasRoute: ContasRoute,
  DespesasRoute: DespesasRoute,
  FinanceiroRoute: FinanceiroRoute,
  LoginRoute: LoginRoute,
  MotoristasRoute: MotoristasRoute,
  RelatoriosRoute: RelatoriosRoute,
  ServicosRoute: ServicosRoute,
  UsuariosRoute: UsuariosRoute,
  VeiculosRoute: VeiculosRoute,
  ApiPublicWhatsappRoute: ApiPublicWhatsappRoute,
  ApiPublicHooksDailySummaryRoute: ApiPublicHooksDailySummaryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
